/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gimnasio.vista;

import gimnasio.controlador.ControladorPrincipal;
import gimnasio.herramientas.excepciones.Notificaciones;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Family
 */
public class JInternalReporteIngresos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalReporteIngresos
     */
    ControladorPrincipal miControlador;
    public JInternalReporteIngresos(ControladorPrincipal miControlador) {
        this.miControlador = miControlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnIngresosEgresosHoy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pickerDesde = new com.github.lgooddatepicker.components.DatePicker();
        pickerHasta = new com.github.lgooddatepicker.components.DatePicker();
        btnReporteDias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("REPORTES DE INGRESOS CON HUELLA");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gimnasio/imagenes/countryIcon.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));

        btnIngresosEgresosHoy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIngresosEgresosHoy.setText("GENERAR REPORTE DE INGRESOS Y EGRESOS");
        btnIngresosEgresosHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosEgresosHoyActionPerformed(evt);
            }
        });
        jPanel3.add(btnIngresosEgresosHoy);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jButton2.setText("CERRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnReporteDias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporteDias.setText("<html><center>Generar Reporte<br>por rango de días</center></html>");
        btnReporteDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteDiasActionPerformed(evt);
            }
        });

        jLabel1.setText("Desde:");

        jLabel2.setText("Hasta:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pickerDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pickerHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReporteDias, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporteDias, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(pickerDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pickerHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnIngresosEgresosHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosEgresosHoyActionPerformed
        try{
        this.miControlador.generarReporteIngresosEgresosHoy();
        }catch(Notificaciones ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnIngresosEgresosHoyActionPerformed

    private void btnReporteDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDiasActionPerformed
        try{
        if (pickerDesde.getDate() != null && pickerHasta.getDate() != null) {
            LocalDate desde = pickerDesde.getDate();
            LocalDate hasta = pickerHasta.getDate();

            if (desde.isBefore(hasta)) {
                    miControlador.generarReporteIngresosPorDia(desde, hasta);
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar un rango de fechas valido.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar un rango de fechas.");
        }
        }catch(Notificaciones ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnReporteDiasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresosEgresosHoy;
    private javax.swing.JButton btnReporteDias;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.github.lgooddatepicker.components.DatePicker pickerDesde;
    private com.github.lgooddatepicker.components.DatePicker pickerHasta;
    // End of variables declaration//GEN-END:variables
}
