/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gimnasio.vista;

import gimnasio.controlador.ControladorPrincipal;
import gimnasio.herramientas.excepciones.Notificaciones;
import gimnasio.modelo.Usuario;
import static gimnasio.vista.MainMenu.miControlador;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author adrian
 */
public class jInternalLogueo extends javax.swing.JInternalFrame {

    /**
     * Creates new form jInternalLogueo
     */
    private String usuario;
    private String pass;
    private ControladorPrincipal controlador;

    public jInternalLogueo(ControladorPrincipal controlador) {
        this.controlador = controlador;
        initComponents();
        this.txtUsuario.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("- ACCSESO AL SISTEMA -");
        setAlignmentX(2.0F);
        setAlignmentY(2.0F);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gimnasio/imagenes/countryIcon.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUsuario)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnAceptar.setText("Ingresar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAceptar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        if (!this.txtUsuario.getText().isEmpty() && !this.txtContrasena.getText().isEmpty()) {
            Usuario unUsuario = controlador.buscarUsuario(txtUsuario.getText(), new String(txtContrasena.getPassword()));
            if (unUsuario == null) {
                JOptionPane.showMessageDialog(null, "Usuario no encontrado.");
                this.txtUsuario.setText("");
                this.txtContrasena.setText("");
                this.txtUsuario.requestFocusInWindow();
            } else {
                MainMenu.loguearUsuario(unUsuario);
                JOptionPane.showMessageDialog(null, "Logueado con exito");
                String[] opciones = {"SI", "NO"};
                int seleccion = JOptionPane.showOptionDialog(null, "¿Desea marcar todas las salidas y asistencias que no se registraron?", "Seleccione una opcion", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);
                switch (seleccion) {
                    case 0:
                        try {
                            miControlador.marcarTodasLasSalidas();
                            miControlador.marcarTodasLasAsistenciasSinSalida();
                        } catch (Notificaciones ex) {
                            JOptionPane.showMessageDialog(null, "Excepcion: Alguna salida no ha podido ser registrada");
                            ex.printStackTrace();
                        }
                        break;
                    case 1:
                        System.out.println("Procediendo sin marcar salidas anteriores");
                        break;
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        if (!this.txtUsuario.getText().isEmpty() && !this.txtContrasena.getText().isEmpty()) {
            Usuario unUsuario = controlador.buscarUsuario(txtUsuario.getText(), new String(txtContrasena.getPassword()));
            if (unUsuario == null) {
                JOptionPane.showMessageDialog(null, "Usuario no encontrado.");
                this.txtUsuario.setText("");
                this.txtContrasena.setText("");
                this.txtUsuario.requestFocusInWindow();
            } else {
                MainMenu.loguearUsuario(unUsuario);
                JOptionPane.showMessageDialog(null, "Logueado con exito");
                String[] opciones = {"SI", "NO"};
                int seleccion = JOptionPane.showOptionDialog(null, "¿Desea marcar todas las salidas y asistencias que no se registraron?", "Seleccione una opcion", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);
                switch (seleccion) {
                    case 0:
                        try {
                            miControlador.marcarTodasLasSalidas();
                            miControlador.marcarTodasLasAsistenciasSinSalida();
                        } catch (Notificaciones ex) {
                            JOptionPane.showMessageDialog(null, "Excepcion: Alguna salida no ha podido ser registrada");
                            ex.printStackTrace();
                        }
                        break;
                    case 1:
                        System.out.println("Procediendo sin marcar salidas anteriores");
                        break;
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void txtContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyTyped
        if (evt.equals(KeyEvent.VK_ENTER)) {
        }
    }//GEN-LAST:event_txtContrasenaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
