/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gimnasio.vista;

import gimnasio.controlador.ControladorPrincipal;
import gimnasio.herramientas.excepciones.Notificaciones;
import gimnasio.modelo.Cajadiaria;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Family
 */
public class JOptionCajasAbiertas extends javax.swing.JDialog {

    
    DefaultTableModel modeloTablaSinCerrar;
    DefaultTableModel modeloTablaCerradas;
    ControladorPrincipal miControlador;
    /**
     * Creates new form JOptionCajasAbiertas
     */
    public JOptionCajasAbiertas(java.awt.Frame parent, boolean modal, ControladorPrincipal miControlador) {
        super(parent, modal);
        this.miControlador = miControlador;
        initComponents();
        this.dateTimePicker1.setLocale(new Locale("es", "ES"));
        cargarTablaSinCierre();
        cargarTablaCerradas();
    }

    public void cargarTablaCerradas(){
        modeloTablaCerradas = new DefaultTableModel();;
        modeloTablaCerradas.addColumn("Fecha");
        modeloTablaCerradas.addColumn("Apertura");
        modeloTablaCerradas.addColumn("Cierre");
        modeloTablaCerradas.addColumn("Usuario");
        this.tablaCajasCerradas.setModel(modeloTablaCerradas);
    }
    public void cargarTablaSinCierre(){
        modeloTablaSinCerrar = new DefaultTableModel();
        modeloTablaSinCerrar.addColumn("Fecha");
        modeloTablaSinCerrar.addColumn("Hora");
        modeloTablaSinCerrar.addColumn("Usuario");
        Object[] fila = new Object[3];
        try{
            for(Cajadiaria caja : miControlador.dameCajasSinCerrar()) {
                fila[0] = caja;
                fila[1] = caja.getAperturaString();
                fila[2] = caja.getEstado();
                modeloTablaSinCerrar.addRow(fila);
            }
        }catch(Notificaciones ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }finally{
            this.tablaCajasSinCierre.setModel(modeloTablaSinCerrar);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCajasSinCierre = new javax.swing.JTable();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCajasCerradas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sin Cierre"));

        tablaCajasSinCierre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCajasSinCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCajasSinCierreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCajasSinCierre);

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("FINALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cerradas"));

        tablaCajasCerradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCajasCerradas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(dateTimePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(dateTimePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCajasSinCierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCajasSinCierreMouseClicked
        if(!tablaCajasSinCierre.getSelectionModel().isSelectionEmpty()){
            Cajadiaria cajaSeleccionada = (Cajadiaria) tablaCajasSinCierre.getValueAt(tablaCajasSinCierre.getSelectedRow(), 0);
            LocalDate fecha = Instant.ofEpochMilli(cajaSeleccionada.getApertura().getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
            this.dateTimePicker1.datePicker.setDate(fecha);
            this.dateTimePicker1.timePicker.setTime(LocalTime.of(23, 59, 59));
        }
    }//GEN-LAST:event_tablaCajasSinCierreMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!tablaCajasSinCierre.getSelectionModel().isSelectionEmpty()){
            try {
                Cajadiaria cajaSeleccionada = (Cajadiaria) tablaCajasSinCierre.getValueAt(tablaCajasSinCierre.getSelectedRow(), 0);
                LocalDateTime fechaSeleccionada = dateTimePicker1.getDateTimePermissive();
                Date cierre = Date.from(fechaSeleccionada.atZone(ZoneId.systemDefault()).toInstant());
                cajaSeleccionada.setCierre(cierre);
                miControlador.altaCaja(cajaSeleccionada);
                this.modeloTablaSinCerrar.removeRow(tablaCajasSinCierre.getSelectedRow());
                Object[] fila = new Object[4];
                fila[0] = cajaSeleccionada;
                fila[1] = cajaSeleccionada.getAperturaString();
                fila[2] = cajaSeleccionada.getCierreString();
                fila[3] = cajaSeleccionada.getEstado();
                this.modeloTablaCerradas.addRow(fila);
            } catch (Notificaciones ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCajasCerradas;
    private javax.swing.JTable tablaCajasSinCierre;
    // End of variables declaration//GEN-END:variables
}
