/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gimnasio.vista;


import com.sun.jna.Native;
import gimnasio.interfaces.GestorRele;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author adrian
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    jInternalLogueo panelLogin = new jInternalLogueo();
    jInternalProductos panelProductos = new jInternalProductos();
    jInternalInformes panelInformes = new jInternalInformes();
    jInternalClases panelClases = new jInternalClases();
    jTemporal panelTemporal = new jTemporal();
    jInternalUsuarios panelUsuarios = new jInternalUsuarios();
    
    boolean mostrar = false;

    GestorRele gestorRele = (GestorRele)Native.load("usb_relay_device", GestorRele.class);
    int res = gestorRele.usb_relay_init();
    GestorRele.usb_relay_device_info.ByReference disp = gestorRele.usb_relay_device_enumerate();
    int handle = gestorRele.usb_relay_device_open(disp);
    
    
    public void actualizarTabla(){
    }
    
    public void cerrarSesion(){
        this.jBtnClases.setEnabled(false);
        this.jBtnInformes.setEnabled(false);
        this.jBtnProductos.setEnabled(false);
        this.jBtnSocios.setEnabled(false);
    }
    
    public MainMenu() {
        initComponents();
        this.jBtnClases.setEnabled(mostrar);
        this.jBtnInformes.setEnabled(mostrar);
        this.jBtnProductos.setEnabled(mostrar);
        this.jBtnSocios.setEnabled(mostrar);
        
        jDesktopPane1.add(panelTemporal);
        jDesktopPane1.add(panelLogin);
        jDesktopPane1.add(panelInformes);
        jDesktopPane1.add(panelProductos);
        jDesktopPane1.add(panelClases);
        jDesktopPane1.add(panelUsuarios);
        
        this.setBtnsVisibility(false);
        
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension loginSize = panelLogin.getSize();
       
        panelLogin.setLocation((desktopSize.width - loginSize.width)/2, (desktopSize.height - loginSize.height)/2);
        panelLogin.setVisible(true);
    }
    
    public javax.swing.JTable getTablaUsuarios(){
       // return this.jTable1;
    }
    
    public jInternalLogueo getjInternalLogueo(){
        return this.panelLogin;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtnSocios = new javax.swing.JButton();
        jBtnProductos = new javax.swing.JButton();
        jBtnClases = new javax.swing.JButton();
        jBtnInformes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtHabilitado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMiArchivo1 = new javax.swing.JMenuItem();
        jMenuEdicion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jBtnSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users(1).png"))); // NOI18N
        jBtnSocios.setText("Usuarios");
        jBtnSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSociosActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnSocios);

        jBtnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/layers.png"))); // NOI18N
        jBtnProductos.setText("Productos/Ventas");
        jBtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProductosActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnProductos);

        jBtnClases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notebook.png"))); // NOI18N
        jBtnClases.setText("Clases/Cupos");
        jBtnClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClasesActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnClases);

        jBtnInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendar.png"))); // NOI18N
        jBtnInformes.setText("Informes/Economia");
        jBtnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInformesActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnInformes);

        jPanel1.add(jPanel2, java.awt.BorderLayout.EAST);

        jButton1.setText("<html><center>ABRIR<br>PUERTA</center></html>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Acceso"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("CARA DEL CHABON");

        txtHabilitado.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHabilitado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jDesktopPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(800, 400));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list.png"))); // NOI18N
        jMenuArchivo.setText("Archivo");

        jMiArchivo1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMiArchivo1.setText("Cerrar Sesion");
        jMiArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiArchivo1ActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMiArchivo1);

        jMenuBar1.add(jMenuArchivo);

        jMenuEdicion.setText("Editar");
        jMenuBar1.add(jMenuEdicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMiArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiArchivo1ActionPerformed
        this.cerrarSesion();
    }//GEN-LAST:event_jMiArchivo1ActionPerformed

    private void jBtnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInformesActionPerformed
        panelInformes.setVisible(true);
    }//GEN-LAST:event_jBtnInformesActionPerformed

    private void jBtnClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClasesActionPerformed
        panelTemporal.setVisible(true);
    }//GEN-LAST:event_jBtnClasesActionPerformed

    private void jBtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProductosActionPerformed
        panelProductos.setVisible(true);
    }//GEN-LAST:event_jBtnProductosActionPerformed

    private void jBtnSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSociosActionPerformed
        panelUsuarios.setVisible(true);
    }//GEN-LAST:event_jBtnSociosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        res = gestorRele.usb_relay_device_open_one_relay_channel(handle,1);
        System.out.println(res);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        res = gestorRele.usb_relay_device_close_one_relay_channel(handle,1);
        System.out.println(res);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClases;
    private javax.swing.JButton jBtnInformes;
    private javax.swing.JButton jBtnProductos;
    private javax.swing.JButton jBtnSocios;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdicion;
    private javax.swing.JMenuItem jMiArchivo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtHabilitado;
    // End of variables declaration//GEN-END:variables

    public void setBtnsVisibility(boolean b) {
        this.jBtnClases.setEnabled(!b);
        this.jBtnInformes.setEnabled(!b);
        this.jBtnProductos.setEnabled(!b);
        this.jBtnSocios.setEnabled(!b);
        this.jMenuArchivo.setEnabled(!b);
        this.jMenuEdicion.setEnabled(!b);
    }

}
