/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gimnasio.vista;

import gimnasio.controlador.ControladorPrincipal;
import gimnasio.herramientas.excepciones.Notificaciones;
import gimnasio.modelo.Cajadiaria;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Family
 */
public class PanelControlCajas extends javax.swing.JPanel {

    DefaultTableModel modeloTablaCajas;
    ControladorPrincipal miControlador;
    TableRowSorter<TableModel> rowSorter;
    Cajadiaria caja = null;
    /**
     * Creates new form NewJPanel
     */
    public PanelControlCajas(ControladorPrincipal miControlador) {
        this.miControlador = miControlador;
        initComponents();
        timeApertura.setLocale(new Locale("es","ES"));
        timeCierre.setLocale(new Locale("es","ES"));
        cargarTablaCajas();
    }

    /**
     * Metodo que carga una tabla de cajasDiarias
     */
    public void cargarTablaCajas(){
        modeloTablaCajas = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloTablaCajas.addColumn("IdCaja");
        modeloTablaCajas.addColumn("Usuario");
        modeloTablaCajas.addColumn("Monto Apertura");
        modeloTablaCajas.addColumn("Dia");
        modeloTablaCajas.addColumn("Hora de Cierre");
        Object[] fila = new Object[5];
        try{
            for(Cajadiaria caja:miControlador.getListaCajas()){
                fila[0] = caja.getIdcaja();
                fila[1] = caja.getEstado();
                fila[2] = caja.getMontoactual();
                fila[3] = caja;
                fila[4] = caja.getCierreString();
                modeloTablaCajas.addRow(fila);
            }
            
        this.jTable1.setModel(modeloTablaCajas);
        rowSorter = new TableRowSorter<>(this.jTable1.getModel());
        jTable1.setRowSorter(rowSorter);
        
        }catch(Notificaciones ex){
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIdCaja = new javax.swing.JTextField();
        txtNombreusuario = new javax.swing.JTextField();
        txtMontoApertura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        timeApertura = new com.github.lgooddatepicker.components.DateTimePicker();
        timeCierre = new com.github.lgooddatepicker.components.DateTimePicker();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Cajas"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtIdCaja.setEditable(false);

        txtNombreusuario.setEditable(false);

        jLabel1.setText("Identificador:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Monto Apertura:");

        jLabel4.setText("Dia/Hora Apertura:");

        jLabel5.setText("Dia/Hora Cierre:");

        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMontoApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(timeCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtras)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(timeApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(timeCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnAtras))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(!jTable1.getSelectionModel().isSelectionEmpty()){
            caja = (Cajadiaria) jTable1.getValueAt(jTable1.getSelectedRow(),3);
            this.txtIdCaja.setText(String.valueOf(caja.getIdcaja()));
            this.txtMontoApertura.setText(String.valueOf(caja.getMontoactual()));
            this.txtNombreusuario.setText(caja.getEstado());
            Instant instante = caja.getApertura().toInstant();
            LocalDateTime apertura = instante.atZone(ZoneId.systemDefault()).toLocalDateTime();
            this.timeApertura.setDateTimePermissive(apertura);
            instante = caja.getCierre().toInstant();
            apertura = instante.atZone(ZoneId.systemDefault()).toLocalDateTime();
            this.timeCierre.setDateTimePermissive(apertura);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(caja!=null){
            try{
            caja.setMontoactual(Double.valueOf(txtMontoApertura.getText()));
            Instant instante = timeApertura.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant();
            Date fecha = Date.from(instante);
            caja.setApertura(fecha);
            instante = timeCierre.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant();
            fecha = Date.from(instante);
            caja.setCierre(fecha);
            miControlador.getMiPersistencia().actualizarInstancia(caja);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "El monto que desea guardar es invalido.");
            }catch(Notificaciones e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido una excepcion con la base de datos");
                e.printStackTrace();
            }finally{
                limpiarCampos();
            }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.github.lgooddatepicker.components.DateTimePicker timeApertura;
    private com.github.lgooddatepicker.components.DateTimePicker timeCierre;
    private javax.swing.JTextField txtIdCaja;
    private javax.swing.JTextField txtMontoApertura;
    private javax.swing.JTextField txtNombreusuario;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        caja = null;
        this.timeApertura.setDateTimePermissive(null);
        this.timeCierre.setDateTimePermissive(null);
        this.txtIdCaja.setText("");
        this.txtMontoApertura.setText("");
        this.txtNombreusuario.setText("");
    }
}
