package gimnasio.modelo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsistenciaProfesorId generated by hbm2java
 */
public class AsistenciaProfesorId  implements java.io.Serializable {


     private int idclase;
     private Date ingreso;

    public AsistenciaProfesorId() {
    }

    public AsistenciaProfesorId(int idclase, Date ingreso) {
       this.idclase = idclase;
       this.ingreso = ingreso;
    }
   
    public int getIdclase() {
        return this.idclase;
    }
    
    public void setIdclase(int idclase) {
        this.idclase = idclase;
    }
    public Date getIngreso() {
        return this.ingreso;
    }
    
    public void setIngreso(Date ingreso) {
        this.ingreso = ingreso;
    }




}


