package gimnasio.modelo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClaseAlumno generated by hbm2java
 */
public class ClaseAlumno  implements java.io.Serializable {


     private int idclasealumno;
     private Alumno alumno;
     private Clase clase;
     private int cantidadclases;
     private String estado;
     private Set asistenciaAlumnos = new HashSet(0);

    public ClaseAlumno() {
    }

	
    public ClaseAlumno(int idclasealumno, Alumno alumno, Clase clase, int cantidadclases) {
        this.idclasealumno = idclasealumno;
        this.alumno = alumno;
        this.clase = clase;
        this.cantidadclases = cantidadclases;
    }
    public ClaseAlumno(int idclasealumno, Alumno alumno, Clase clase, int cantidadclases, String estado, Set asistenciaAlumnos) {
       this.idclasealumno = idclasealumno;
       this.alumno = alumno;
       this.clase = clase;
       this.cantidadclases = cantidadclases;
       this.estado = estado;
       this.asistenciaAlumnos = asistenciaAlumnos;
    }
   
    public int getIdclasealumno() {
        return this.idclasealumno;
    }
    
    public void setIdclasealumno(int idclasealumno) {
        this.idclasealumno = idclasealumno;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public int getCantidadclases() {
        return this.cantidadclases;
    }
    
    public void setCantidadclases(int cantidadclases) {
        this.cantidadclases = cantidadclases;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getAsistenciaAlumnos() {
        return this.asistenciaAlumnos;
    }
    
    public void setAsistenciaAlumnos(Set asistenciaAlumnos) {
        this.asistenciaAlumnos = asistenciaAlumnos;
    }




}


