package gimnasio.modelo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private int idclase;
     private Profesormodalidad profesormodalidad;
     private Sector sector;
     private Date horainicio;
     private Date horafin;
     private String estado;
     private Set asistenciaProfesors = new HashSet(0);
     private Set cuotas = new HashSet(0);
     private Set claseAlumnos = new HashSet(0);

    public Clase() {
    }

	
    public Clase(int idclase, Profesormodalidad profesormodalidad, Sector sector) {
        this.idclase = idclase;
        this.profesormodalidad = profesormodalidad;
        this.sector = sector;
    }
    public Clase(int idclase, Profesormodalidad profesormodalidad, Sector sector, Date horainicio, Date horafin, String estado, Set asistenciaProfesors, Set cuotas, Set claseAlumnos) {
       this.idclase = idclase;
       this.profesormodalidad = profesormodalidad;
       this.sector = sector;
       this.horainicio = horainicio;
       this.horafin = horafin;
       this.estado = estado;
       this.asistenciaProfesors = asistenciaProfesors;
       this.cuotas = cuotas;
       this.claseAlumnos = claseAlumnos;
    }
   
    public int getIdclase() {
        return this.idclase;
    }
    
    public void setIdclase(int idclase) {
        this.idclase = idclase;
    }
    public Profesormodalidad getProfesormodalidad() {
        return this.profesormodalidad;
    }
    
    public void setProfesormodalidad(Profesormodalidad profesormodalidad) {
        this.profesormodalidad = profesormodalidad;
    }
    public Sector getSector() {
        return this.sector;
    }
    
    public void setSector(Sector sector) {
        this.sector = sector;
    }
    public Date getHorainicio() {
        return this.horainicio;
    }
    
    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }
    public Date getHorafin() {
        return this.horafin;
    }
    
    public void setHorafin(Date horafin) {
        this.horafin = horafin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getAsistenciaProfesors() {
        return this.asistenciaProfesors;
    }
    
    public void setAsistenciaProfesors(Set asistenciaProfesors) {
        this.asistenciaProfesors = asistenciaProfesors;
    }
    public Set getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Set cuotas) {
        this.cuotas = cuotas;
    }
    public Set getClaseAlumnos() {
        return this.claseAlumnos;
    }
    
    public void setClaseAlumnos(Set claseAlumnos) {
        this.claseAlumnos = claseAlumnos;
    }




}


