package gimnasio.modelo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private int idcontacto;
     private String direccion;
     private String telefono1;
     private String telefono2;
     private String email1;
     private String telefonoemergencia;
     private Set obrasocials = new HashSet(0);

    public Contacto() {
    }

	
    public Contacto(int idcontacto, String direccion) {
        this.idcontacto = idcontacto;
        this.direccion = direccion;
    }
    public Contacto(int idcontacto, String direccion, String telefono1, String telefono2, String email1, String telefonoemergencia, Set obrasocials) {
       this.idcontacto = idcontacto;
       this.direccion = direccion;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.email1 = email1;
       this.telefonoemergencia = telefonoemergencia;
       this.obrasocials = obrasocials;
    }
   
    public int getIdcontacto() {
        return this.idcontacto;
    }
    
    public void setIdcontacto(int idcontacto) {
        this.idcontacto = idcontacto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }
    public String getTelefonoemergencia() {
        return this.telefonoemergencia;
    }
    
    public void setTelefonoemergencia(String telefonoemergencia) {
        this.telefonoemergencia = telefonoemergencia;
    }
    public Set getObrasocials() {
        return this.obrasocials;
    }
    
    public void setObrasocials(Set obrasocials) {
        this.obrasocials = obrasocials;
    }




}


