package gimnasio.modelo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private int idmodulo;
     private Sistema sistema;
     private String nombremodulo;
     private String estadomodulo;
     private Set usuarios = new HashSet(0);

    public Modulo() {
    }

	
    public Modulo(int idmodulo, Sistema sistema, String nombremodulo) {
        this.idmodulo = idmodulo;
        this.sistema = sistema;
        this.nombremodulo = nombremodulo;
    }
    public Modulo(int idmodulo, Sistema sistema, String nombremodulo, String estadomodulo, Set usuarios) {
       this.idmodulo = idmodulo;
       this.sistema = sistema;
       this.nombremodulo = nombremodulo;
       this.estadomodulo = estadomodulo;
       this.usuarios = usuarios;
    }
   
    public int getIdmodulo() {
        return this.idmodulo;
    }
    
    public void setIdmodulo(int idmodulo) {
        this.idmodulo = idmodulo;
    }
    public Sistema getSistema() {
        return this.sistema;
    }
    
    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    public String getNombremodulo() {
        return this.nombremodulo;
    }
    
    public void setNombremodulo(String nombremodulo) {
        this.nombremodulo = nombremodulo;
    }
    public String getEstadomodulo() {
        return this.estadomodulo;
    }
    
    public void setEstadomodulo(String estadomodulo) {
        this.estadomodulo = estadomodulo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


