package gimnasio.modelo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesormodalidad generated by hbm2java
 */
public class Profesormodalidad  implements java.io.Serializable {


     private int idprofesormodalidad;
     private Modalidad modalidad;
     private Profesor profesor;
     private Double preciohora;
     private String estado;
     private Set clases = new HashSet(0);

    public Profesormodalidad() {
    }

	
    public Profesormodalidad(int idprofesormodalidad, Modalidad modalidad, Profesor profesor) {
        this.idprofesormodalidad = idprofesormodalidad;
        this.modalidad = modalidad;
        this.profesor = profesor;
    }
    public Profesormodalidad(int idprofesormodalidad, Modalidad modalidad, Profesor profesor, Double preciohora, String estado, Set clases) {
       this.idprofesormodalidad = idprofesormodalidad;
       this.modalidad = modalidad;
       this.profesor = profesor;
       this.preciohora = preciohora;
       this.estado = estado;
       this.clases = clases;
    }
   
    public int getIdprofesormodalidad() {
        return this.idprofesormodalidad;
    }
    
    public void setIdprofesormodalidad(int idprofesormodalidad) {
        this.idprofesormodalidad = idprofesormodalidad;
    }
    public Modalidad getModalidad() {
        return this.modalidad;
    }
    
    public void setModalidad(Modalidad modalidad) {
        this.modalidad = modalidad;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Double getPreciohora() {
        return this.preciohora;
    }
    
    public void setPreciohora(Double preciohora) {
        this.preciohora = preciohora;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getClases() {
        return this.clases;
    }
    
    public void setClases(Set clases) {
        this.clases = clases;
    }




}


