package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1


import gimnasio.herramientas.excepciones.Notificaciones;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Alumno generated by hbm2java RECONTRAtouched by Osoft
 */
public class Alumno  implements java.io.Serializable {


     private int idalumno;
     private Contacto contacto;
     private Obrasocial obrasocial;
     private Usuario usuario;
     private String nombrealumno;
     private String apellidoalumno;
     private Double peso;
     private Double altura;
     private Date fechanacimiento;
     private String estado;
     private Set<ClaseAlumno> claseAlumnos = new HashSet(0);
     private Set<Cuota> cuotas = new HashSet(0);
     private Set inscripcions = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(Contacto contacto, Obrasocial obrasocial, Usuario usuario, String nombrealumno, String apellidoalumno, String estado) {
        this.contacto = contacto;
        this.obrasocial = obrasocial;
        this.usuario = usuario;
        this.nombrealumno = nombrealumno;
        this.apellidoalumno = apellidoalumno;
        this.estado = estado;
    }
    public Alumno(Contacto contacto, Obrasocial obrasocial, Usuario usuario, String nombrealumno, String apellidoalumno, Double peso, Double altura, Date fechanacimiento, String estado) {
       this.contacto = contacto;
       this.obrasocial = obrasocial;
       this.usuario = usuario;
       this.nombrealumno = nombrealumno;
       this.apellidoalumno = apellidoalumno;
       this.peso = peso;
       this.altura = altura;
       this.fechanacimiento = fechanacimiento;
       this.estado = estado;
       this.claseAlumnos = claseAlumnos;
       this.cuotas = cuotas;
       this.inscripcions = inscripcions;
    }

    public Alumno(Contacto unContacto, Usuario usuarioSeleccionado, String nombre, String apellido, Double peso, Double altura, Date fecha, String activo) {
       this.contacto = unContacto;
       this.usuario = usuarioSeleccionado;
       this.nombrealumno = nombre;
       this.apellidoalumno = apellido;
       this.peso = peso;
       this.altura = altura;
       this.fechanacimiento = fecha;
       this.estado = activo;
       this.claseAlumnos = claseAlumnos;
       this.cuotas = cuotas;
       this.inscripcions = inscripcions;
    }
   
    public int getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }
    public Obrasocial getObrasocial() {
        return this.obrasocial;
    }
    
    public void setObrasocial(Obrasocial obrasocial) {
        this.obrasocial = obrasocial;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombrealumno() {
        return this.nombrealumno;
    }
    
    public void setNombrealumno(String nombrealumno) {
        this.nombrealumno = nombrealumno;
    }
    public String getApellidoalumno() {
        return this.apellidoalumno;
    }
    
    public void setApellidoalumno(String apellidoalumno) {
        this.apellidoalumno = apellidoalumno;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Double getAltura() {
        return this.altura;
    }
    
    public void setAltura(Double altura) {
        this.altura = altura;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<ClaseAlumno> getClaseAlumnos() {
        return this.claseAlumnos;
    }
    
    public void setClaseAlumnos(Set<ClaseAlumno> claseAlumnos) {
        this.claseAlumnos = claseAlumnos;
    }
    public Set<Cuota> getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Set<Cuota> cuotas) {
        this.cuotas = cuotas;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }

    @Override
    public String toString() {
        return nombrealumno;
    }

    public Cuota getLastCuota(){
        List<Cuota> listaCuotas = new ArrayList<>();
        listaCuotas.addAll(cuotas);
        Collections.sort(listaCuotas);
        Cuota unaCuota = null;
        try{
            for(Cuota cuota:listaCuotas){
                System.out.println(cuota + " estado: " + cuota.getEstado());
            }
            unaCuota = listaCuotas.get(listaCuotas.size()-1);
        }catch(ArrayIndexOutOfBoundsException ex){
            unaCuota = new Cuota();
        }
        return unaCuota;
    }

    public Cuota getUltimaCuotaImpaga(){
        List<Cuota> listaCuotas = new ArrayList<>();
        listaCuotas.addAll(cuotas);
        Collections.sort(listaCuotas);
        Cuota esaCuota = null;
        for(Cuota unaCuota:listaCuotas){
            if(unaCuota.getEstado().equalsIgnoreCase("ADEUDA")
                    || unaCuota.getEstado().equalsIgnoreCase("SALDO")){
                esaCuota = unaCuota;
                break;
            }
        }
        return esaCuota;
    }
    
    public Cuota getUltimaCuota() throws Notificaciones{
        List<Cuota> listaCuotas = new ArrayList<>();
        listaCuotas.addAll(cuotas);
        Collections.sort(listaCuotas);
        int i = listaCuotas.size();
        if(i==0){
            throw new Notificaciones("No posee cuotas");
        }
        return listaCuotas.get(i-1);
    }



}


