package gimnasio.modelo;
// Generated 03/12/2018 19:24:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idalumno;
     private Usuario usuario;
     private String nombrealumno;
     private String apellidoalumno;
     private Integer edad;
     private Double peso;
     private Double altura;
     private String estado;
     private Date fechacumpleanios;
     private Set claseAlumnos = new HashSet(0);
     private Set cuotas = new HashSet(0);
     private Set inscripcions = new HashSet(0);

    public Alumno() {
    }

    public Alumno(String nombrealumno, String apellido){
        this.apellidoalumno = apellido;
        this.nombrealumno = nombrealumno;
    }
	
    public Alumno(Usuario usuario, String nombrealumno, String apellidoalumno) {
        this.usuario = usuario;
        this.nombrealumno = nombrealumno;
        this.apellidoalumno = apellidoalumno;
    }
    public Alumno(Usuario usuario, String nombrealumno, String apellidoalumno, Integer edad, Double peso, Double altura, String estado, Date fechacumpleanios) {
       this.usuario = usuario;
       this.nombrealumno = nombrealumno;
       this.apellidoalumno = apellidoalumno;
       this.edad = edad;
       this.peso = peso;
       this.altura = altura;
       this.estado = estado;
       this.fechacumpleanios = fechacumpleanios;
    }
   
    public int getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombrealumno() {
        return this.nombrealumno;
    }
    
    public void setNombrealumno(String nombrealumno) {
        this.nombrealumno = nombrealumno;
    }
    public String getApellidoalumno() {
        return this.apellidoalumno;
    }
    
    public void setApellidoalumno(String apellidoalumno) {
        this.apellidoalumno = apellidoalumno;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Double getAltura() {
        return this.altura;
    }
    
    public void setAltura(Double altura) {
        this.altura = altura;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechacumpleanios() {
        return this.fechacumpleanios;
    }
    
    public void setFechacumpleanios(Date fechacumpleanios) {
        this.fechacumpleanios = fechacumpleanios;
    }
    public Set getClaseAlumnos() {
        return this.claseAlumnos;
    }
    
    public void setClaseAlumnos(Set claseAlumnos) {
        this.claseAlumnos = claseAlumnos;
    }
    public Set getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Set cuotas) {
        this.cuotas = cuotas;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }




}


