package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AperturaCajaDiaria generated by hbm2java
 */
public class AperturaCajaDiaria  implements java.io.Serializable {


     private int idapertura;
     private Personal personal;
     private int idcaja;
     private Date apertura;
     private String estado;

    public AperturaCajaDiaria() {
    }

    public AperturaCajaDiaria(int idapertura, Personal personal, int idcaja, Date apertura, String estado) {
       this.idapertura = idapertura;
       this.personal = personal;
       this.idcaja = idcaja;
       this.apertura = apertura;
       this.estado = estado;
    }
   
    public int getIdapertura() {
        return this.idapertura;
    }
    
    public void setIdapertura(int idapertura) {
        this.idapertura = idapertura;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public int getIdcaja() {
        return this.idcaja;
    }
    
    public void setIdcaja(int idcaja) {
        this.idcaja = idcaja;
    }
    public Date getApertura() {
        return this.apertura;
    }
    
    public void setApertura(Date apertura) {
        this.apertura = apertura;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


