package gimnasio.modelo;
// Generated 03/12/2018 19:24:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsistenciaProfesorId generated by hbm2java
 */
public class AsistenciaProfesorId  implements java.io.Serializable {


     private int idclase;
     private Date ingreso;

    public AsistenciaProfesorId() {
    }

    public AsistenciaProfesorId(int idclase, Date ingreso) {
       this.idclase = idclase;
       this.ingreso = ingreso;
    }
   
    public int getIdclase() {
        return this.idclase;
    }
    
    public void setIdclase(int idclase) {
        this.idclase = idclase;
    }
    public Date getIngreso() {
        return this.ingreso;
    }
    
    public void setIngreso(Date ingreso) {
        this.ingreso = ingreso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsistenciaProfesorId) ) return false;
		 AsistenciaProfesorId castOther = ( AsistenciaProfesorId ) other; 
         
		 return (this.getIdclase()==castOther.getIdclase())
 && ( (this.getIngreso()==castOther.getIngreso()) || ( this.getIngreso()!=null && castOther.getIngreso()!=null && this.getIngreso().equals(castOther.getIngreso()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdclase();
         result = 37 * result + ( getIngreso() == null ? 0 : this.getIngreso().hashCode() );
         return result;
   }   


}


