package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsistenciaAlumno generated by hbm2java
 */
public class AsistenciaAlumno  implements java.io.Serializable {


     private int id;
     private ClaseAlumno claseAlumno;
     private Date ingreso;
     private Date salida;
     private String estado;

    public AsistenciaAlumno() {
    }

	
    public AsistenciaAlumno(int id, ClaseAlumno claseAlumno, String estado) {
        this.id = id;
        this.claseAlumno = claseAlumno;
        this.estado = estado;
    }
    
    public AsistenciaAlumno(int id, ClaseAlumno claseAlumno, Date ingreso, String estado) {
       this.id = id;
       this.claseAlumno = claseAlumno;
       this.ingreso = ingreso;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ClaseAlumno getClaseAlumno() {
        return this.claseAlumno;
    }
    
    public void setClaseAlumno(ClaseAlumno claseAlumno) {
        this.claseAlumno = claseAlumno;
    }
    public Date getSalida() {
        return this.salida;
    }
    
    public void setSalida(Date salida) {
        this.salida = salida;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getIngreso() {
        return ingreso;
    }

    public void setIngreso(Date ingreso) {
        this.ingreso = ingreso;
    }

    
    
    @Override
    public String toString() {
        return claseAlumno.getAlumno().getNombrealumno() + " " + claseAlumno.getAlumno().getApellidoalumno();
    }
   
}


