package gimnasio.modelo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Cajadiaria generated by hbm2java
 */
public class Cajadiaria  implements java.io.Serializable, Comparable {


     private int idcaja;
     private double montoactual;
     private Personal personal;
     private Date apertura;
     private Date cierre;
     private String estado;

    public Cajadiaria() {
    }

	
    public Cajadiaria(Personal personal, Double montoactual, Date apertura, Date cierre, String estado) {
       this.personal = personal;
       this.montoactual = montoactual;;
       this.apertura = apertura;
       this.cierre = cierre;
       this.estado = estado;
    }

    public Cajadiaria(double montoactual, Date apertura, String estado) {
        this.montoactual = montoactual;
        this.apertura = apertura;
        this.estado = estado;
    }
   
    
    
    public int getIdcaja() {
        return this.idcaja;
    }
    
    public void setIdcaja(int idcaja) {
        this.idcaja = idcaja;
    }
    public double getMontoactual() {
        return this.montoactual;
    }
    
    public void setMontoactual(double montoactual) {
        this.montoactual = montoactual;
    }
     
    public void setApertura(Date apertura) {
        this.apertura = apertura;
    }
    public Date getApertura() {
        return this.apertura;
    }
    
      public void setCierre(Date cierre) {
        this.cierre = cierre;
    }
    public Date getCierre() {
        return this.cierre;
    }

    public Personal getPersonal() {
        return personal;
    }

    public void setPersonal(Personal personal) {
        this.personal = personal;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Override
    public int compareTo(Object o) {
        int retorno = 0;
        Cajadiaria other =(Cajadiaria) o;
        if(this.apertura.before(other.apertura)){
            retorno = -1;
        }
        if(this.apertura.after(other.apertura)){
            retorno = 1;
        }
        return retorno;
    }

    public String getAperturaString() {
        SimpleDateFormat sdf = new SimpleDateFormat();
        sdf.applyPattern("HH:mm");
        return  sdf.format(apertura);
    }

    @Override
    public String toString() {
        SimpleDateFormat formato = new SimpleDateFormat("EEEE", new Locale("es", "ES"));
        String fecha = formato.format(apertura);
        return fecha;
    }

    public String getCierreString() {
        SimpleDateFormat sdf = new SimpleDateFormat();
        sdf.applyPattern("HH:mm");
        return sdf.format(cierre);
    }
    
    
    
    
    
}


