package gimnasio.modelo;
// Generated 03/12/2018 19:24:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private int idcargo;
     private String nombrecargo;
     private String descripcioncargo;
     private Set usuarios = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String nombrecargo) {
        this.nombrecargo = nombrecargo;
    }
    public Cargo(String nombrecargo, String descripcioncargo, Set usuario) {
       this.nombrecargo = nombrecargo;
       this.descripcioncargo = descripcioncargo;
       this.usuarios = usuario;
    }
   
    public int getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(int idcargo) {
        this.idcargo = idcargo;
    }
    public String getNombrecargo() {
        return this.nombrecargo;
    }
    
    public void setNombrecargo(String nombrecargo) {
        this.nombrecargo = nombrecargo;
    }
    public String getDescripcioncargo() {
        return this.descripcioncargo;
    }
    
    public void setDescripcioncargo(String descripcioncargo) {
        this.descripcioncargo = descripcioncargo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


