package modelonuevo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private int idclase;
     private String tipoclase;
     private Integer alumnosmaximo;
     private String descripcionclase;
     private String estado;
     private Set cuotas = new HashSet(0);
     private Set claseProfesors = new HashSet(0);

    public Clase() {
    }

	
    public Clase(int idclase, String tipoclase, String estado) {
        this.idclase = idclase;
        this.tipoclase = tipoclase;
        this.estado = estado;
    }
    public Clase(int idclase, String tipoclase, Integer alumnosmaximo, String descripcionclase, String estado, Set cuotas, Set claseProfesors) {
       this.idclase = idclase;
       this.tipoclase = tipoclase;
       this.alumnosmaximo = alumnosmaximo;
       this.descripcionclase = descripcionclase;
       this.estado = estado;
       this.cuotas = cuotas;
       this.claseProfesors = claseProfesors;
    }
   
    public int getIdclase() {
        return this.idclase;
    }
    
    public void setIdclase(int idclase) {
        this.idclase = idclase;
    }
    public String getTipoclase() {
        return this.tipoclase;
    }
    
    public void setTipoclase(String tipoclase) {
        this.tipoclase = tipoclase;
    }
    public Integer getAlumnosmaximo() {
        return this.alumnosmaximo;
    }
    
    public void setAlumnosmaximo(Integer alumnosmaximo) {
        this.alumnosmaximo = alumnosmaximo;
    }
    public String getDescripcionclase() {
        return this.descripcionclase;
    }
    
    public void setDescripcionclase(String descripcionclase) {
        this.descripcionclase = descripcionclase;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Set cuotas) {
        this.cuotas = cuotas;
    }
    public Set getClaseProfesors() {
        return this.claseProfesors;
    }
    
    public void setClaseProfesors(Set claseProfesors) {
        this.claseProfesors = claseProfesors;
    }




}


