package modelonuevo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private int idcontacto;
     private String direccion;
     private String telefono1;
     private String telefono2;
     private String email1;
     private String telefonoemergencia;
     private String estado;
     private Set obrasocials = new HashSet(0);
     private Set alumnos = new HashSet(0);
     private Set personals = new HashSet(0);
     private Set profesors = new HashSet(0);

    public Contacto() {
    }

	
    public Contacto(int idcontacto, String estado) {
        this.idcontacto = idcontacto;
        this.estado = estado;
    }
    public Contacto(int idcontacto, String direccion, String telefono1, String telefono2, String email1, String telefonoemergencia, String estado, Set obrasocials, Set alumnos, Set personals, Set profesors) {
       this.idcontacto = idcontacto;
       this.direccion = direccion;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.email1 = email1;
       this.telefonoemergencia = telefonoemergencia;
       this.estado = estado;
       this.obrasocials = obrasocials;
       this.alumnos = alumnos;
       this.personals = personals;
       this.profesors = profesors;
    }
   
    public int getIdcontacto() {
        return this.idcontacto;
    }
    
    public void setIdcontacto(int idcontacto) {
        this.idcontacto = idcontacto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }
    public String getTelefonoemergencia() {
        return this.telefonoemergencia;
    }
    
    public void setTelefonoemergencia(String telefonoemergencia) {
        this.telefonoemergencia = telefonoemergencia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getObrasocials() {
        return this.obrasocials;
    }
    
    public void setObrasocials(Set obrasocials) {
        this.obrasocials = obrasocials;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }




}


