package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuota generated by hbm2java
 */
public class Cuota  implements java.io.Serializable {


     private int idcuota;
     private Alumno alumno;
     private ClaseProfesor claseProfesor;
     private Double monto;
     private Date altacuota;
     private Date vencimiento;
     private String estado;
     private Set cobroCuotas = new HashSet(0);

    public Cuota() {
    }

	
    public Cuota(int idcuota, Alumno alumno, ClaseProfesor claseProfesor, Date altacuota, Date vencimiento, String estado) {
        this.idcuota = idcuota;
        this.alumno = alumno;
        this.claseProfesor = claseProfesor;
        this.altacuota = altacuota;
        this.vencimiento = vencimiento;
        this.estado = estado;
    }
    public Cuota(int idcuota, Alumno alumno, ClaseProfesor claseProfesor, Double monto, Date altacuota, Date vencimiento, String estado, Set cobroCuotas) {
       this.idcuota = idcuota;
       this.alumno = alumno;
       this.claseProfesor = claseProfesor;
       this.monto = monto;
       this.altacuota = altacuota;
       this.vencimiento = vencimiento;
       this.estado = estado;
       this.cobroCuotas = cobroCuotas;
    }
   
    public int getIdcuota() {
        return this.idcuota;
    }
    
    public void setIdcuota(int idcuota) {
        this.idcuota = idcuota;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Date getAltacuota() {
        return this.altacuota;
    }
    
    public void setAltacuota(Date altacuota) {
        this.altacuota = altacuota;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCobroCuotas() {
        return this.cobroCuotas;
    }
    
    public void setCobroCuotas(Set cobroCuotas) {
        this.cobroCuotas = cobroCuotas;
    }

    public ClaseProfesor getClaseProfesor() {
        return claseProfesor;
    }

    public void setClaseProfesor(ClaseProfesor claseProfesor) {
        this.claseProfesor = claseProfesor;
    }    
    
    @Override
    public String toString() {
        return alumno.getNombrealumno() + " " + alumno.getApellidoalumno();
    }


}


