package modelonuevo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuota generated by hbm2java
 */
public class Cuota  implements java.io.Serializable {


     private int idcuota;
     private Alumno alumno;
     private Clase clase;
     private Double monto;
     private Date altacuota;
     private Date vencimiento;
     private String estado;
     private Set cobroCuotas = new HashSet(0);

    public Cuota() {
    }

	
    public Cuota(int idcuota, Alumno alumno, Clase clase, Date altacuota, Date vencimiento, String estado) {
        this.idcuota = idcuota;
        this.alumno = alumno;
        this.clase = clase;
        this.altacuota = altacuota;
        this.vencimiento = vencimiento;
        this.estado = estado;
    }
    public Cuota(int idcuota, Alumno alumno, Clase clase, Double monto, Date altacuota, Date vencimiento, String estado, Set cobroCuotas) {
       this.idcuota = idcuota;
       this.alumno = alumno;
       this.clase = clase;
       this.monto = monto;
       this.altacuota = altacuota;
       this.vencimiento = vencimiento;
       this.estado = estado;
       this.cobroCuotas = cobroCuotas;
    }
   
    public int getIdcuota() {
        return this.idcuota;
    }
    
    public void setIdcuota(int idcuota) {
        this.idcuota = idcuota;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Date getAltacuota() {
        return this.altacuota;
    }
    
    public void setAltacuota(Date altacuota) {
        this.altacuota = altacuota;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCobroCuotas() {
        return this.cobroCuotas;
    }
    
    public void setCobroCuotas(Set cobroCuotas) {
        this.cobroCuotas = cobroCuotas;
    }




}


