package modelonuevo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modalidad generated by hbm2java
 */
public class Modalidad  implements java.io.Serializable {


     private int idmodalidad;
     private String nombremodalidad;
     private String descripcionmodalidad;
     private String estado;
     private Set profesorModalidads = new HashSet(0);
     private Set claseProfesors = new HashSet(0);

    public Modalidad() {
    }

	
    public Modalidad(int idmodalidad, String nombremodalidad, String estado) {
        this.idmodalidad = idmodalidad;
        this.nombremodalidad = nombremodalidad;
        this.estado = estado;
    }
    public Modalidad(int idmodalidad, String nombremodalidad, String descripcionmodalidad, String estado, Set profesorModalidads, Set claseProfesors) {
       this.idmodalidad = idmodalidad;
       this.nombremodalidad = nombremodalidad;
       this.descripcionmodalidad = descripcionmodalidad;
       this.estado = estado;
       this.profesorModalidads = profesorModalidads;
       this.claseProfesors = claseProfesors;
    }
   
    public int getIdmodalidad() {
        return this.idmodalidad;
    }
    
    public void setIdmodalidad(int idmodalidad) {
        this.idmodalidad = idmodalidad;
    }
    public String getNombremodalidad() {
        return this.nombremodalidad;
    }
    
    public void setNombremodalidad(String nombremodalidad) {
        this.nombremodalidad = nombremodalidad;
    }
    public String getDescripcionmodalidad() {
        return this.descripcionmodalidad;
    }
    
    public void setDescripcionmodalidad(String descripcionmodalidad) {
        this.descripcionmodalidad = descripcionmodalidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getProfesorModalidads() {
        return this.profesorModalidads;
    }
    
    public void setProfesorModalidads(Set profesorModalidads) {
        this.profesorModalidads = profesorModalidads;
    }
    public Set getClaseProfesors() {
        return this.claseProfesors;
    }
    
    public void setClaseProfesors(Set claseProfesors) {
        this.claseProfesors = claseProfesors;
    }




}


