package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Obrasocial generated by hbm2java
 */
public class Obrasocial  implements java.io.Serializable {


     private int idobrasocial;
     private Contacto contacto;
     private String nombreobrasocial;
     private String estado;
     private Set alumnos = new HashSet(0);
     private Set personals = new HashSet(0);
     private Set profesors = new HashSet(0);

    public Obrasocial() {
    }

    public Obrasocial(String toString){
        this.nombreobrasocial = toString;
    }
    
    public Obrasocial(Contacto contacto, String nombreobrasocial) {
        this.contacto = contacto;
        this.nombreobrasocial = nombreobrasocial;
    }
	
    public Obrasocial(Contacto contacto, String nombreobrasocial, String estado) {
        this.idobrasocial = idobrasocial;
        this.contacto = contacto;
        this.nombreobrasocial = nombreobrasocial;
        this.estado = estado;
    }
   
    public int getIdobrasocial() {
        return this.idobrasocial;
    }
    
    public void setIdobrasocial(int idobrasocial) {
        this.idobrasocial = idobrasocial;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }
    public String getNombreobrasocial() {
        return this.nombreobrasocial;
    }
    
    public void setNombreobrasocial(String nombreobrasocial) {
        this.nombreobrasocial = nombreobrasocial;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }

    @Override
    public String toString() {
        return  nombreobrasocial;
    }

    @Override
    public boolean equals(Object obj) {
        boolean retorno = false;
                if(this == obj){
            retorno = true;
        }
        if(obj == null){
            retorno = false;
        }else{
                if(getClass() != obj.getClass()){
                    retorno = false;
                }
                try{
                Obrasocial comparador = (Obrasocial)obj;
                if(this.getIdobrasocial()== comparador.getIdobrasocial()){
                    retorno = true;
                }
                }catch (ClassCastException ex){
                    return false;
                }
        }
        
        return retorno; 
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + this.idobrasocial;
        return hash;
    }

    
}


