package modelonuevo;
// Generated Dec 7, 2018 12:25:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Obrasocial generated by hbm2java
 */
public class Obrasocial  implements java.io.Serializable {


     private int idobrasocial;
     private Contacto contacto;
     private String nombreobrasocial;
     private String estado;
     private Set alumnos = new HashSet(0);
     private Set personals = new HashSet(0);
     private Set profesors = new HashSet(0);

    public Obrasocial() {
    }

	
    public Obrasocial(int idobrasocial, Contacto contacto, String nombreobrasocial, String estado) {
        this.idobrasocial = idobrasocial;
        this.contacto = contacto;
        this.nombreobrasocial = nombreobrasocial;
        this.estado = estado;
    }
    public Obrasocial(int idobrasocial, Contacto contacto, String nombreobrasocial, String estado, Set alumnos, Set personals, Set profesors) {
       this.idobrasocial = idobrasocial;
       this.contacto = contacto;
       this.nombreobrasocial = nombreobrasocial;
       this.estado = estado;
       this.alumnos = alumnos;
       this.personals = personals;
       this.profesors = profesors;
    }
   
    public int getIdobrasocial() {
        return this.idobrasocial;
    }
    
    public void setIdobrasocial(int idobrasocial) {
        this.idobrasocial = idobrasocial;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }
    public String getNombreobrasocial() {
        return this.nombreobrasocial;
    }
    
    public void setNombreobrasocial(String nombreobrasocial) {
        this.nombreobrasocial = nombreobrasocial;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }




}


