package gimnasio.modelo;
// Generated 03/12/2018 19:24:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PagoProfesor generated by hbm2java
 */
public class PagoProfesor  implements java.io.Serializable {


     private int idpagoprofesor;
     private Profesor profesor;
     private double montopago;
     private Date fechapago;

    public PagoProfesor() {
    }

    public PagoProfesor(int idpagoprofesor, Profesor profesor, double montopago, Date fechapago) {
       this.idpagoprofesor = idpagoprofesor;
       this.profesor = profesor;
       this.montopago = montopago;
       this.fechapago = fechapago;
    }
   
    public int getIdpagoprofesor() {
        return this.idpagoprofesor;
    }
    
    public void setIdpagoprofesor(int idpagoprofesor) {
        this.idpagoprofesor = idpagoprofesor;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public double getMontopago() {
        return this.montopago;
    }
    
    public void setMontopago(double montopago) {
        this.montopago = montopago;
    }
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }




}


