package gimnasio.modelo;
// Generated 03/12/2018 19:24:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int idprofesor;
     private Usuario usuario;
     private int idcontacto;
     private Integer idobrasocial;
     private String nombreprofesor;
     private String apellidoprofesor;
     private Double peso;
     private Double altura;
     private String estado;
     private Date fechanacimiento;
     private Set pagoProfesors = new HashSet(0);
     private Set profesormodalidads = new HashSet(0);

    public Profesor() {
    }

    
    public Profesor(Usuario usuario, String nombreProfesor, String apellidoProfesor, String esatado){
        this.usuario = usuario;
        this.nombreprofesor = nombreProfesor;
        this.apellidoprofesor = apellidoProfesor;
        this.estado = estado;
    }
	
    public Profesor(Usuario usuario, int idcontacto, String nombreprofesor, String apellidoprofesor, String estado) {
        this.usuario = usuario;
        this.idcontacto = idcontacto;
        this.nombreprofesor = nombreprofesor;
        this.apellidoprofesor = apellidoprofesor;
        this.estado = estado;
    }
    public Profesor(Usuario usuario, int idcontacto, Integer idobrasocial, String nombreprofesor, String apellidoprofesor, Integer edad, Double peso, Double altura, String estado, Date fechanacimiento) {
       this.usuario = usuario;
       this.idcontacto = idcontacto;
       this.idobrasocial = idobrasocial;
       this.nombreprofesor = nombreprofesor;
       this.apellidoprofesor = apellidoprofesor;
       this.peso = peso;
       this.altura = altura;
       this.estado = estado;
       this.fechanacimiento = fechanacimiento;

    }
   
    public int getIdprofesor() {
        return this.idprofesor;
    }
    
    public void setIdprofesor(int idprofesor) {
        this.idprofesor = idprofesor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getIdcontacto() {
        return this.idcontacto;
    }
    
    public void setIdcontacto(int idcontacto) {
        this.idcontacto = idcontacto;
    }
    public Integer getIdobrasocial() {
        return this.idobrasocial;
    }
    
    public void setIdobrasocial(Integer idobrasocial) {
        this.idobrasocial = idobrasocial;
    }
    public String getNombreprofesor() {
        return this.nombreprofesor;
    }
    
    public void setNombreprofesor(String nombreprofesor) {
        this.nombreprofesor = nombreprofesor;
    }
    public String getApellidoprofesor() {
        return this.apellidoprofesor;
    }
    
    public void setApellidoprofesor(String apellidoprofesor) {
        this.apellidoprofesor = apellidoprofesor;
    }

    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Double getAltura() {
        return this.altura;
    }
    
    public void setAltura(Double altura) {
        this.altura = altura;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechanacimiento() {
        return fechanacimiento;
    }

    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    
    
    public Set getPagoProfesors() {
        return this.pagoProfesors;
    }
    
    public void setPagoProfesors(Set pagoProfesors) {
        this.pagoProfesors = pagoProfesors;
    }
    public Set getProfesormodalidads() {
        return this.profesormodalidads;
    }
    
    public void setProfesormodalidads(Set profesormodalidads) {
        this.profesormodalidads = profesormodalidads;
    }




}


