package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1



/**
 * Saldopagoprofesor generated by hbm2java
 */
public class Saldopagoprofesor  implements java.io.Serializable {


     private int idsaldopago;
     private CobroCuota cobroCuota;
     private double montosaldo;
     private String estado;

    public Saldopagoprofesor() {
    }

    public Saldopagoprofesor(int idsaldopago, CobroCuota cobroCuota, double montosaldo, String estado) {
       this.idsaldopago = idsaldopago;
       this.cobroCuota = cobroCuota;
       this.montosaldo = montosaldo;
       this.estado = estado;
    }
   
    public int getIdsaldopago() {
        return this.idsaldopago;
    }
    
    public void setIdsaldopago(int idsaldopago) {
        this.idsaldopago = idsaldopago;
    }
    public CobroCuota getCobroCuota() {
        return this.cobroCuota;
    }
    
    public void setCobroCuota(CobroCuota cobroCuota) {
        this.cobroCuota = cobroCuota;
    }
    public double getMontosaldo() {
        return this.montosaldo;
    }
    
    public void setMontosaldo(double montosaldo) {
        this.montosaldo = montosaldo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


