package gimnasio.modelo;
// Generated 03/12/2018 19:24:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private int idsector;
     private String nombresector;
     private String descripcionsector;
     private String estado;
     private Set clases = new HashSet(0);

    public Sector() {
    }

	
    public Sector(int idsector, String nombresector, String estado) {
        this.idsector = idsector;
        this.nombresector = nombresector;
        this.estado = estado;
    }
    public Sector(int idsector, String nombresector, String descripcionsector, String estado) {
       this.idsector = idsector;
       this.nombresector = nombresector;
       this.descripcionsector = descripcionsector;
       this.estado = estado;
    }
   
    public int getIdsector() {
        return this.idsector;
    }
    
    public void setIdsector(int idsector) {
        this.idsector = idsector;
    }
    public String getNombresector() {
        return this.nombresector;
    }
    
    public void setNombresector(String nombresector) {
        this.nombresector = nombresector;
    }
    public String getDescripcionsector() {
        return this.descripcionsector;
    }
    
    public void setDescripcionsector(String descripcionsector) {
        this.descripcionsector = descripcionsector;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    
    
    public Set getClases() {
        return this.clases;
    }
    
    public void setClases(Set clases) {
        this.clases = clases;
    }




}


