package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private int idsector;
     private String nombresector;
     private String descripcionsector;
     private String estado;
     private Set sectorClases = new HashSet(0);

    public Sector() {
    }

	
    public Sector(int idsector, String nombresector, String estado) {
        this.idsector = idsector;
        this.nombresector = nombresector;
        this.estado = estado;
    }
    public Sector(int idsector, String nombresector, String descripcionsector, String estado, Set sectorClases) {
       this.idsector = idsector;
       this.nombresector = nombresector;
       this.descripcionsector = descripcionsector;
       this.estado = estado;
       this.sectorClases = sectorClases;
    }
   
    public int getIdsector() {
        return this.idsector;
    }
    
    public void setIdsector(int idsector) {
        this.idsector = idsector;
    }
    public String getNombresector() {
        return this.nombresector;
    }
    
    public void setNombresector(String nombresector) {
        this.nombresector = nombresector;
    }
    public String getDescripcionsector() {
        return this.descripcionsector;
    }
    
    public void setDescripcionsector(String descripcionsector) {
        this.descripcionsector = descripcionsector;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getSectorClases() {
        return this.sectorClases;
    }
    
    public void setSectorClases(Set sectorClases) {
        this.sectorClases = sectorClases;
    }




}


