package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1



/**
 * UsuarioModuloId generated by hbm2java
 */
public class UsuarioModuloId  implements java.io.Serializable {


     private int idusuario;
     private int idmodulo;

    public UsuarioModuloId() {
    }

    public UsuarioModuloId(int idusuario, int idmodulo) {
       this.idusuario = idusuario;
       this.idmodulo = idmodulo;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public int getIdmodulo() {
        return this.idmodulo;
    }
    
    public void setIdmodulo(int idmodulo) {
        this.idmodulo = idmodulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioModuloId) ) return false;
		 UsuarioModuloId castOther = ( UsuarioModuloId ) other; 
         
		 return (this.getIdusuario()==castOther.getIdusuario())
 && (this.getIdmodulo()==castOther.getIdmodulo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdusuario();
         result = 37 * result + this.getIdmodulo();
         return result;
   }   


}


