package gimnasio.modelo;
// Generated Dec 8, 2018 5:14:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombreusuario;
     private String contrasenia;
     private byte[] planillahuellas;
     private byte[] foto;
     private String estado;
     private Set usuarioModulos = new HashSet(0);
     private Set personals = new HashSet(0);
     private Set profesors = new HashSet(0);
     private Set alumnos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombreusuario, String contrasenia, String estado) {
        this.nombreusuario = nombreusuario;
        this.estado = estado;
    }
    
    public Usuario(String nombreusuario, String contrasenia, byte[] planillahuellas, byte[] foto, String estado) {
       this.nombreusuario = nombreusuario;
       this.contrasenia = contrasenia;
       this.planillahuellas = planillahuellas;
       this.foto = foto;
       this.estado = estado;
    }
   
    public Usuario(String nombreusuario, String contrasenia, byte[] planillahuellas, byte[] foto) {
       this.nombreusuario = nombreusuario;
       this.contrasenia = contrasenia;
       this.planillahuellas = planillahuellas;
       this.foto = foto;
    }
    
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public byte[] getPlanillahuellas() {
        return this.planillahuellas;
    }
    
    public void setPlanillahuellas(byte[] planillahuellas) {
        this.planillahuellas = planillahuellas;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getUsuarioModulos() {
        return this.usuarioModulos;
    }
    
    public void setUsuarioModulos(Set usuarioModulos) {
        this.usuarioModulos = usuarioModulos;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }

    @Override
    public String toString() {
        return nombreusuario;
    }

}


