package gimnasio.modelo;
// Generated 03/12/2018 19:24:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombreusuario;
     private String contrasenia;
     private byte[] planillahuellas;
     private byte[] foto;
     private String estado;
     private Set modulos = new HashSet(0);
     private Set cargos = new HashSet(0);
     private Set profesors = new HashSet(0);
     private Set alumnos = new HashSet(0);

    public Usuario() {
    }
    
    public Usuario(String nombreusuario, String contrasenia, byte[] planillahuellas, byte[] foto, String estado) {
       this.nombreusuario = nombreusuario;
       this.contrasenia = contrasenia;
       this.planillahuellas = planillahuellas;
       this.foto = foto;
       this.estado = estado;
    }
    
    public Usuario(String nombreUsuario, String contrasenia, String estado){
        this.nombreusuario= nombreUsuario;
        this.contrasenia = contrasenia;
        this.estado = estado;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public byte[] getPlanillahuellas() {
        return this.planillahuellas;
    }
    
    public void setPlanillahuellas(byte[] planillahuellas) {
        this.planillahuellas = planillahuellas;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Set getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set modulos) {
        this.modulos = modulos;
    }
    public Set getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set cargos) {
        this.cargos = cargos;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }

    @Override
    public String toString() {
        return nombreusuario;
    }




}


